package id.epost.pos;

import android.app.*; import android.graphics.*; import android.graphics.drawable.GradientDrawable; import android.os.Bundle; import android.text.InputType; import android.view.*; import android.widget.*;
import java.text.SimpleDateFormat; import java.util.*;
import id.epost.pos.data.DemoRepository; import id.epost.pos.model.*; import id.epost.pos.tenant.TenantContext; import id.epost.pos.util.Money;

public class MainActivity extends Activity {
 private static final int INK=Color.rgb(15,23,42), MUTED=Color.rgb(100,116,139), GREEN=Color.rgb(5,150,105), BG=Color.rgb(248,250,252);
 private final DemoRepository repo=new DemoRepository(); private final List<CartItem> cart=new ArrayList<>(); private TenantContext tenant; private LinearLayout content; private TextView cartBadge;
 @Override public void onCreate(Bundle b){super.onCreate(b);showLogin();}
 private GradientDrawable bg(int color,int radius){GradientDrawable g=new GradientDrawable();g.setColor(color);g.setCornerRadius(dp(radius));return g;}
 private void shell(String page){
  LinearLayout root=col();root.setBackgroundColor(BG);
  LinearLayout top=row();top.setPadding(dp(20),dp(16),dp(20),dp(12));TextView brand=txt("EPOST",23,true,INK);top.addView(brand,new LinearLayout.LayoutParams(0,-2,1));top.addView(txt(page,14,true,MUTED));root.addView(top);
  content=col();content.setPadding(dp(18),dp(8),dp(18),dp(28));ScrollView sv=new ScrollView(this);sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));
  LinearLayout nav=row();nav.setPadding(dp(8),dp(6),dp(8),dp(8));nav.setBackgroundColor(Color.WHITE);nav.addView(nav("Beranda",v->showHome()),wt());nav.addView(nav("POS",v->showPOS()),wt());nav.addView(nav("Transaksi",v->showTransactions()),wt());nav.addView(nav("Lainnya",v->showOutlet()),wt());root.addView(nav);setContentView(root);
 }
 private void showLogin(){
  LinearLayout page=col();page.setPadding(dp(28),dp(46),dp(28),dp(28));page.setBackgroundColor(Color.WHITE);
  TextView logo=txt("EPOST",32,true,INK);page.addView(logo);page.addView(txt("\nSelamat Datang 👋",28,true,INK));page.addView(txt("Masuk ke akun Anda\n",16,false,MUTED));
  EditText code=input("Tenant");code.setText("DEMO");EditText email=input("Email");email.setText("cashier@demo.id");EditText pass=input("Password");pass.setInputType(InputType.TYPE_CLASS_TEXT|InputType.TYPE_TEXT_VARIATION_PASSWORD);pass.setText("demo");
  page.addView(code);page.addView(email);page.addView(pass);Button enter=primary("Masuk");enter.setOnClickListener(v->{String x=code.getText().toString().trim();if(x.isEmpty()){code.setError("Tenant wajib diisi");return;}tenant=new TenantContext(x.toLowerCase(Locale.ROOT),"Demo Store","OUTLET-01");showHome();});page.addView(enter);page.addView(txt("\nMulti-tenant • Offline Ready • Secure",12,false,MUTED));setContentView(page);
 }
 private void showHome(){shell("Beranda");content.addView(txt("Halo, Cashier Demo",25,true,INK));content.addView(txt(tenant.tenantName()+" • Outlet Utama\n",14,false,MUTED));
  LinearLayout sales=card();sales.setBackground(bg(GREEN,18));sales.addView(txt("Penjualan Hari Ini",13,false,Color.WHITE));sales.addView(txt("Rp 1.248.500",28,true,Color.WHITE));sales.addView(txt("12 transaksi  •  34 item",13,false,Color.WHITE));content.addView(sales);
  content.addView(txt("\nMenu Cepat",17,true,INK));LinearLayout quick=row();quick.addView(tile("🛒\nPenjualan",v->showPOS()),wt());quick.addView(tile("▣\nProduk",v->showPOS()),wt());quick.addView(tile("↻\nRiwayat",v->showTransactions()),wt());content.addView(quick);
  content.addView(txt("\nTransaksi Terbaru",17,true,INK));content.addView(txt("#TRX-0012                         Rp 45.000\n2 item                                      09:14",14,true,INK));
 }
 private void showPOS(){shell("Produk");EditText s=input("Cari produk / SKU");content.addView(s);LinearLayout cats=row();cats.addView(chip("Semua"),wt());cats.addView(chip("Minuman"),wt());cats.addView(chip("Makanan"),wt());content.addView(cats);cartBadge=txt("\n"+cartText(),15,true,GREEN);content.addView(cartBadge);for(Product p:repo.products(tenant))addProduct(p);Button checkout=primary("Lihat Keranjang & Checkout");checkout.setOnClickListener(v->showCart());content.addView(checkout);}
 private void addProduct(Product p){LinearLayout c=card();LinearLayout line=row();TextView info=txt(p.name+"\n"+p.sku+" • Stok "+p.stock+"\n"+Money.idr(p.price),16,true,INK);Button add=small("+");add.setOnClickListener(v->{addCart(p);cartBadge.setText("\n"+cartText());});line.addView(info,new LinearLayout.LayoutParams(0,-2,1));line.addView(add);c.addView(line);content.addView(c);}
 private void showCart(){shell("Keranjang");if(cart.isEmpty()){content.addView(txt("Keranjang masih kosong.",16,false,MUTED));return;}for(CartItem i:cart)content.addView(txt(i.product.name+"   × "+i.qty+"\n"+Money.idr(i.subtotal()),16,true,INK));content.addView(txt("\nSubtotal                         "+Money.idr(total())+"\nDiskon                           Rp 0\nPajak (0%)                       Rp 0\n\nTOTAL                            "+Money.idr(total()),16,true,INK));Button pay=primary("Lanjut ke Pembayaran →");pay.setOnClickListener(v->checkout());content.addView(pay);}
 private void addCart(Product p){for(CartItem i:cart)if(i.product.id.equals(p.id)){i.qty++;return;}cart.add(new CartItem(p,1));}
 private long total(){long n=0;for(CartItem i:cart)n+=i.subtotal();return n;}private int qty(){int n=0;for(CartItem i:cart)n+=i.qty;return n;}private String cartText(){return qty()+" item • "+Money.idr(total());}
 private void checkout(){if(cart.isEmpty()){toast("Keranjang masih kosong");return;}new AlertDialog.Builder(this).setTitle("Pembayaran Tunai").setMessage("Total\n"+Money.idr(total())+"\n\nKonfirmasi pembayaran?").setNegativeButton("Batal",null).setPositiveButton("Bayar",(d,w)->complete()).show();}
 private void complete(){String now=new SimpleDateFormat("dd MMM yyyy HH:mm",new Locale("id","ID")).format(new Date());long paid=total();repo.save(new Transaction("TRX-"+System.currentTimeMillis(),tenant.tenantId(),tenant.outletId(),paid,"TUNAI",now));cart.clear();new AlertDialog.Builder(this).setTitle("✓ Transaksi Berhasil!").setMessage("Pembayaran "+Money.idr(paid)+" berhasil disimpan.").setPositiveButton("Lihat Riwayat",(d,w)->showTransactions()).setNegativeButton("Transaksi Baru",(d,w)->showPOS()).show();}
 private void showTransactions(){shell("Riwayat Transaksi");content.addView(input("Cari nomor transaksi..."));List<Transaction> list=repo.transactions(tenant);if(list.isEmpty())content.addView(txt("Belum ada transaksi.",16,false,MUTED));for(Transaction t:list){LinearLayout c=card();c.addView(txt(t.id+"                         "+Money.idr(t.total)+"\n"+t.createdAt+" • "+t.paymentMethod,15,true,INK));content.addView(c);}}
 private void showOutlet(){shell("Lainnya");content.addView(txt(tenant.tenantName(),26,true,INK));content.addView(txt("Tenant: "+tenant.tenantId()+"\nOutlet aktif: "+tenant.outletId()+"\nRole: CASHIER\n",15,false,MUTED));Button out=primary("Keluar");out.setOnClickListener(v->{cart.clear();tenant=null;showLogin();});content.addView(out);}
 private LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;}private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER_VERTICAL);return l;}private LinearLayout.LayoutParams wt(){return new LinearLayout.LayoutParams(0,-2,1);}
 private LinearLayout card(){LinearLayout l=col();l.setPadding(dp(16),dp(14),dp(16),dp(14));l.setBackground(bg(Color.WHITE,16));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(6),0,dp(6));l.setLayoutParams(p);l.setElevation(dp(2));return l;}
 private Button primary(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(15);b.setAllCaps(false);b.setBackground(bg(GREEN,14));b.setPadding(dp(12),dp(10),dp(12),dp(10));return b;}private Button small(String s){Button b=primary(s);b.setMinWidth(dp(48));return b;}
 private Button nav(String s,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setTextSize(11);b.setTextColor(MUTED);b.setAllCaps(false);b.setBackgroundColor(Color.TRANSPARENT);b.setOnClickListener(l);return b;}private Button tile(String s,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setTextColor(INK);b.setAllCaps(false);b.setBackground(bg(Color.WHITE,16));b.setOnClickListener(l);return b;}private Button chip(String s){Button b=new Button(this);b.setText(s);b.setTextSize(11);b.setAllCaps(false);return b;}
 private EditText input(String h){EditText e=new EditText(this);e.setHint(h);e.setSingleLine(true);e.setTextColor(INK);e.setHintTextColor(MUTED);e.setBackground(bg(Color.rgb(241,245,249),14));e.setPadding(dp(14),dp(12),dp(14),dp(12));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(6),0,dp(8));e.setLayoutParams(p);return e;}
 private TextView txt(String s,float z,boolean bold,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(color);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);t.setPadding(0,dp(5),0,dp(5));return t;}private void toast(String s){Toast.makeText(this,s,Toast.LENGTH_SHORT).show();}private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
}