package id.epost.pos;

import android.app.*;import android.graphics.Color;import android.graphics.Typeface;import android.os.Bundle;import android.view.*;import android.widget.*;import java.text.SimpleDateFormat;import java.util.*;
import id.epost.pos.data.DemoRepository;import id.epost.pos.model.*;import id.epost.pos.tenant.TenantContext;import id.epost.pos.util.Money;

public class MainActivity extends Activity{
 private static final int INK=Color.rgb(15,23,42),MUTED=Color.rgb(100,116,139),GREEN=Color.rgb(5,150,105);
 private final DemoRepository repo=new DemoRepository();private final List<CartItem> cart=new ArrayList<>();private TenantContext tenant;private LinearLayout content,nav;private TextView outlet;
 @Override public void onCreate(Bundle b){super.onCreate(b);showLogin();}
 private void showLogin(){setContentView(R.layout.screen_login);EditText t=findViewById(R.id.tenantInput),e=findViewById(R.id.emailInput),p=findViewById(R.id.passwordInput);t.setText("DEMO");e.setText("cashier@demo.id");p.setText("demo");findViewById(R.id.loginButton).setOnClickListener(v->{String code=t.getText().toString().trim();if(code.isEmpty()){t.setError("Tenant wajib diisi");return;}tenant=new TenantContext(code.toLowerCase(Locale.ROOT),"Demo Store","OUTLET-01");showHome();});}
 private void shell(){setContentView(R.layout.activity_main);content=findViewById(R.id.content);nav=findViewById(R.id.bottomNav);outlet=findViewById(R.id.headerOutlet);outlet.setText(tenant.tenantName()+" • Outlet Utama");addNav("⌂\nBeranda",v->showHome());addNav("▣\nPOS",v->showPOS());addNav("□\nProduk",v->showPOS());addNav("↻\nTransaksi",v->showTransactions());addNav("•••\nLainnya",v->showOutlet());}
 private void showHome(){shell();content.addView(text("Halo, Cashier Demo",26,true,INK));content.addView(text(tenant.tenantName()+" • Outlet Utama",14,false,MUTED));LinearLayout hero=box(R.drawable.green_card_bg);hero.addView(text("Penjualan Hari Ini",13,false,Color.WHITE));hero.addView(text("Rp 1.248.500",29,true,Color.WHITE));hero.addView(text("12 transaksi  •  34 item                       ↗ 12%",13,false,Color.WHITE));content.addView(hero);content.addView(text("\nMenu Cepat",18,true,INK));LinearLayout q=row();q.addView(menu("▣\nPenjualan\n(POS)",v->showPOS()),wt());q.addView(menu("◇\nProduk",v->showPOS()),wt());q.addView(menu("↻\nRiwayat\nTransaksi",v->showTransactions()),wt());content.addView(q);content.addView(text("\nTransaksi Terbaru",18,true,INK));LinearLayout recent=box(R.drawable.card_bg);recent.addView(text("#TRX-0012                                      Rp 45.000\n2 item                                                   09:14",14,true,INK));content.addView(recent);}
 private void showPOS(){shell();content.addView(text("Produk",25,true,INK));EditText search=new EditText(this);search.setHint("⌕  Cari produk...");search.setSingleLine();search.setPadding(dp(16),0,dp(16),0);search.setBackgroundResource(R.drawable.input_bg);content.addView(search,new LinearLayout.LayoutParams(-1,dp(54)));LinearLayout cats=row();for(String s:new String[]{"Semua","Minuman","Makanan","Snack"})cats.addView(chip(s),wt());content.addView(cats);for(Product p:repo.products(tenant)){LinearLayout card=box(R.drawable.card_bg);LinearLayout line=row();line.addView(text(p.name+"\n"+Money.idr(p.price)+"\nStok "+p.stock,16,true,INK),new LinearLayout.LayoutParams(0,-2,1));Button add=round("+");add.setOnClickListener(v->{add(p);Toast.makeText(this,"Ditambahkan • "+qty()+" item",Toast.LENGTH_SHORT).show();});line.addView(add);card.addView(line);content.addView(card);}Button cartBtn=primary("Keranjang • "+qty()+" item • "+Money.idr(total()));cartBtn.setOnClickListener(v->showCart());content.addView(cartBtn);}
 private void showCart(){shell();content.addView(text("Keranjang",25,true,INK));if(cart.isEmpty()){content.addView(text("\nKeranjang masih kosong.",16,false,MUTED));return;}for(CartItem i:cart){LinearLayout c=box(R.drawable.card_bg);c.addView(text(i.product.name+"                         "+Money.idr(i.subtotal())+"\n−    "+i.qty+"    +",15,true,INK));content.addView(c);}LinearLayout sum=box(R.drawable.card_bg);sum.addView(text("Subtotal                              "+Money.idr(total())+"\nDiskon                                Rp 0\nPajak (0%)                            Rp 0\n\nTotal                                 "+Money.idr(total()),16,true,INK));content.addView(sum);Button b=primary("Lanjut ke Pembayaran →");b.setOnClickListener(v->showPayment());content.addView(b);}
 private void showPayment(){shell();content.addView(text("Pembayaran",25,true,INK));content.addView(text("\nTotal",14,false,MUTED));content.addView(text(Money.idr(total()),34,true,INK));content.addView(text("\nMetode Pembayaran",15,true,INK));LinearLayout methods=row();for(String s:new String[]{"Tunai","QRIS","Kartu","Lainnya"})methods.addView(chip(s),wt());content.addView(methods);EditText cash=new EditText(this);cash.setHint("Uang diterima");cash.setInputType(2);cash.setPadding(dp(16),0,dp(16),0);cash.setBackgroundResource(R.drawable.input_bg);content.addView(cash,new LinearLayout.LayoutParams(-1,dp(56)));Button pay=primary("Selesaikan Transaksi");pay.setOnClickListener(v->complete());content.addView(pay);}
 private void complete(){long paid=total();String now=new SimpleDateFormat("dd MMM yyyy HH:mm",new Locale("id","ID")).format(new Date());repo.save(new Transaction("#TRX-"+System.currentTimeMillis(),tenant.tenantId(),tenant.outletId(),paid,"TUNAI",now));cart.clear();shell();Space sp=new Space(this);content.addView(sp,new LinearLayout.LayoutParams(1,dp(100)));TextView check=text("✓",64,true,GREEN);check.setGravity(Gravity.CENTER);content.addView(check);TextView ok=text("Transaksi Berhasil!",27,true,INK);ok.setGravity(Gravity.CENTER);content.addView(ok);TextView amount=text("Pembayaran "+Money.idr(paid)+" berhasil disimpan.",15,false,MUTED);amount.setGravity(Gravity.CENTER);content.addView(amount);Button history=primary("Lihat Riwayat");history.setOnClickListener(v->showTransactions());content.addView(history);Button fresh=primary("Transaksi Baru");fresh.setOnClickListener(v->showPOS());content.addView(fresh);}
 private void showTransactions(){shell();content.addView(text("Riwayat Transaksi",25,true,INK));List<Transaction> list=repo.transactions(tenant);if(list.isEmpty())content.addView(text("\nBelum ada transaksi.",16,false,MUTED));for(Transaction t:list){LinearLayout c=box(R.drawable.card_bg);c.addView(text(t.id+"                                  "+Money.idr(t.total)+"\n"+t.createdAt+" • "+t.paymentMethod,14,true,INK));content.addView(c);}}
 private void showOutlet(){shell();content.addView(text("Akun & Outlet",25,true,INK));LinearLayout c=box(R.drawable.card_bg);c.addView(text("Cashier Demo\n"+tenant.tenantName()+"\nOutlet Utama\nRole: CASHIER",16,true,INK));content.addView(c);Button b=primary("Keluar");b.setOnClickListener(v->{cart.clear();tenant=null;showLogin();});content.addView(b);}
 private void add(Product p){for(CartItem i:cart)if(i.product.id.equals(p.id)){i.qty++;return;}cart.add(new CartItem(p,1));}private long total(){long n=0;for(CartItem i:cart)n+=i.subtotal();return n;}private int qty(){int n=0;for(CartItem i:cart)n+=i.qty;return n;}
 private LinearLayout box(int bg){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(16),dp(16),dp(16),dp(16));l.setBackgroundResource(bg);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(7),0,dp(7));l.setLayoutParams(p);return l;}private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);l.setGravity(Gravity.CENTER);return l;}private LinearLayout.LayoutParams wt(){return new LinearLayout.LayoutParams(0,-2,1);}
 private TextView text(String s,float z,boolean bold,int color){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setTextColor(color);if(bold)t.setTypeface(Typeface.DEFAULT,Typeface.BOLD);t.setPadding(0,dp(5),0,dp(5));return t;}private Button primary(String s){Button b=new Button(this);b.setText(s);b.setTextColor(Color.WHITE);b.setTextSize(15);b.setAllCaps(false);b.setBackgroundTintList(android.content.res.ColorStateList.valueOf(GREEN));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,dp(56));p.setMargins(0,dp(12),0,0);b.setLayoutParams(p);return b;}
 private Button round(String s){Button b=primary(s);b.setLayoutParams(new LinearLayout.LayoutParams(dp(52),dp(52)));return b;}private Button chip(String s){Button b=new Button(this);b.setText(s);b.setTextSize(11);b.setAllCaps(false);return b;}private Button menu(String s,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setTextColor(INK);b.setTextSize(12);b.setAllCaps(false);b.setBackgroundResource(R.drawable.card_bg);b.setOnClickListener(l);return b;}private void addNav(String s,View.OnClickListener l){Button b=new Button(this);b.setText(s);b.setTextSize(10);b.setTextColor(MUTED);b.setAllCaps(false);b.setBackgroundColor(Color.TRANSPARENT);b.setOnClickListener(l);nav.addView(b,wt());}private int dp(int n){return Math.round(n*getResources().getDisplayMetrics().density);}
}